import requests
import json

names = ['CC Couserans-Pyrénées',
 'CC du Pays de Mirepoix',
 "CC du Pays d'Olmes",
 'CC de la Haute Ariège',
 'CC du Pays de Tarascon',
 'CA Pays Foix-Varilhes',
 'CC Arize Lèze',
 "CC des Portes d'Ariège Pyrénées",
 'CA Carcassonne Agglo',
 'CC Castelnaudary Lauragais Audois',
 'CC du Limouxin',
 'CC Région Lézignanaise, Corbières et Minervois',
 'CA Le Grand Narbonne',
 'CC Pyrénées Audoises',
 'CC Piège Lauragais Malepère',
 'CC de la Montagne Noire',
 'CC Lauragais Revel Sorezois',
 'CC Corbières Salanque Méditerranée',
 'CC du Pays de Salars',
 'CC de Millau Grands Causses',
 'CC du Plateau de Montbazens',
 'CC Decazeville Communauté',
 'CC de Lévézou Pareloup',
 'CC Ouest Aveyron Communauté',
 'CC du Pays Rignacois',
 'CC Monts, Rance et Rougier',
 'CC Grand-Figeac',
 'CC du Réquistanais',
 'CC de la Muse et des Raspes du Tarn',
 'CC Aveyron Bas Ségala Viaur',
 'CC Larzac et Vallées',
 "CC des Causses à l'Aubrac",
 'CC Comtal Lot et Truyère',
 'CC Pays Ségali Communauté',
 'CC Aubrac, Carladez et Viadène',
 'CC Saint Affricain, Roquefort, Sept Vallons',
 'CC Conques-Marcillac',
 'CA Rodez Agglomération',
 "CC Pays d'Uzès",
 'CC du Piémont Cévenol',
 'CC Terre de Camargue',
 'CC Rhony, Vistre, Vidourle',
 'CA du Gard Rhodanien',
 'CC de Petite Camargue',
 'CA Alès Agglomération',
 'CC de Cèze Cévennes',
 'CC du Pays Viganais',
 'CA du Grand Avignon (COGA)',
 'CC du Pont du Gard',
 'CC du Pays de Sommières',
 "CC Beaucaire Terre d'Argence",
 'CA de Nîmes Métropole',
 'CC Causses Aigoual Cévennes',
 'CC Mont Lozère',
 'CC des Cévennes Gangeoises et Suménoises',
 'CC Cœur et Coteaux du Comminges',
 'CC des Terres du Lauragais',
 'Toulouse Métropole',
 'CA du Sicoval',
 'CC Pyrénées Haut Garonnaises',
 'CC Cagire Garonne Salat',
 'CC du Bassin Auterivain Haut-Garonnais',
 'CC Tarn-Agout',
 'CC du Volvestre',
 'CC des Coteaux du Girou',
 'CC Cœur de Garonne',
 'CC des Hauts-Tolosans',
 "CC Val'Aïgo",
 'CA Le Muretain Agglo',
 'CC du Frontonnais',
 'CC des Coteaux Bellevue',
 'CC de la Gascogne Toulousaine',
 'CC Le Grand Ouest Toulousain',
 'CC Armagnac Adour',
 'CC des Coteaux Arrats Gimone',
 'CA Grand Auch Cœur de Gascogne',
 "CC d'Aire-sur-l'Adour",
 'CC du Bas Armagnac',
 'CC Bastides de Lomagne',
 'CC Bastides et Vallons du Gers',
 "CC Cœur d'Astarac en Gascogne",
 'CC Val de Gers',
 'CC Astarac Arros en Gascogne',
 'CC du Grand Armagnac',
 'CC Artagnan de Fezensac',
 'CC de la Tenarèze',
 'CC de la Lomagne Gersoise',
 'CC du Saves',
 'CC des Deux Rives',
 'CC Les Avant-Monts',
 'CA Hérault-Méditerranée',
 'CC du Minervois au Caroux',
 'CC Grand Orb communauté de communes en Languedoc',
 'CA de Béziers-Méditerranée',
 "CC Vallée de l'Hérault",
 'CC du Clermontais',
 'CC du Grand Pic Saint-Loup',
 'CC Sud-Hérault',
 'Montpellier Méditerranée Métropole',
 'CA Sète Agglopôle Méditerranée',
 'CC du Pays de Lunel',
 'CC Lodévois et Larzac',
 'CC des Monts de Lacaune et de la Montagne du Haut Languedoc',
 "CA du Pays de l'Or",
 'CC La Domitienne',
 'CC de la Vallée du Lot et du Vignoble',
 'CC Causses et Vallée de la Dordogne',
 'CC Quercy - Bouriane',
 'CA du Grand Cahors',
 'CC Cazals-Salviac',
 'CC du Pays de Lalbenque-Limogne',
 'CC du Causse de Labastide-Murat',
 'CC du Quercy Blanc',
 "CC des Hautes Terres de l'Aubrac",
 "CC des Terres d'Apcher-Margeride-Aubrac",
 'CC du Gévaudan',
 'CC Randon - Margeride',
 'CC du Haut Allier',
 'CC Cœur de Lozère',
 'CC Aubrac Lot Causses Tarn',
 'CC Gorges Causses Cévennes',
 'CC des Cévennes au Mont Lozère',
 'CC Pyrénées Vallées des Gaves',
 'CA Tarbes-Lourdes-Pyrénées',
 'CC Aure Louron',
 'CC Adour Madiran',
 'CC Neste Barousse',
 'CC du Pays de Trie et du Magnoac',
 'CC de la Haute-Bigorre',
 'CC Pays de Nay',
 'CC du Plateau de Lannemezan',
 "CC des Coteaux du Val d'Arros",
 'CC du Vallespir',
 'CC Sud-Roussillon',
 'CC du Haut Vallespir',
 'CC Pyrénées catalanes',
 'CC Pyrénées Cerdagne',
 'CC Agly Fenouillèdes',
 'CC Conflent-Canigó',
 "CC des Albères, de la Côte Vermeille et de l'Illibéris",
 'CU Perpignan Méditerranée Métropole',
 'CC des Aspres',
 'CC Roussillon-Conflent',
 "CC du Sor et de l'Agout",
 'CA de Castres Mazamet',
 "CC des Monts d'Alban et du Villefranchois",
 "CA de l'Albigeois (C2A)",
 'CC Thoré Montagne Noire',
 'CA Gaillac-Graulhet',
 'CC Carmausin-Ségala',
 'CC du Cordais et du Causse (4 C)',
 'CC Val 81',
 'CC Centre Tarn',
 'CC Sidobre Vals et Plateaux',
 "CC du Lautrécois et du Pays d'Agout",
 "CC du Quercy Rouergue et des Gorges de l'Aveyron",
 'CA Grand Montauban',
 'CC Quercy Vert-Aveyron',
 'CC Terres des Confluences',
 'CC de la Lomagne Tarn-et-Garonnaise',
 'CC Grand Sud Tarn et Garonne',
 'CC du Quercy Caussadais',
 'CC du Pays de Lafrançaise',
 'CC du Pays de Serres en Quercy']

url = "https://etalab-datasets.geo.data.gouv.fr/contours-administratifs/2024/geojson/epci-50m.geojson"

response = requests.get(url)
response.raise_for_status()
geojson_all = response.json()

features_filtered = [
    f for f in geojson_all["features"]
    if f["properties"].get("nom") in names
]

geojson_epci_occ = {
    "type": "FeatureCollection",
    "features": features_filtered,
}

with open("epci_occitanie.geojson", "w", encoding="utf-8") as f:
    json.dump(geojson_epci_occ, f, ensure_ascii=False, indent=2)

print("Nombre d'EPCI conservés :", len(features_filtered))